name: Laravel CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo_mysql
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Set up .env file
      run: cp .env.ci .env

    - name: Generate key
      run: php artisan key:generate

    - name: Migrate database
      run: php artisan migrate --force

    - name: Seed database
      run: php artisan db:seed

    - name: Run Tests
      run: php artisan test
